<style type="text/css">
#section{
	padding-top:10px;
}
#message{
	padding:10px;
	width:90%;
	margin-left: auto; 
	margin-right: auto;
	margin-top:20px;
	border: solid 1px rgb(0, 133, 195);
	border-radius:5px;
	min-height:300px;
}
</style>
<div id ='section'>
<div id='message'>
<img src="<?php echo $this->home.$this->baseUrl.'/img/overairlogo.png';?>" height="48" title="<?php echo getenv('APP_NAME'); ?>&nbsp;<?= \Application\Module::VERSION ?>"/><br/><br/>
We are happy to inform your account has been created in our system!<br><br>
&nbsp;&nbsp;&nbsp;URL :&nbsp;<a href="<?php echo $this->home.$this->baseUrl.'/login';?>"><?php echo $this->home.$this->baseUrl.'/login';?></a><br><br>
Please use these credentials to access the portal: <br><br>
&nbsp;&nbsp;&nbsp;Login Name&nbsp;:&nbsp;<?php echo stripslashes($this->mail);?><br> 
&nbsp;&nbsp;&nbsp;Password&nbsp;:&nbsp;<?php echo stripslashes($this->password);?>
</div>
</div><!-- Content -->