<?php
$this->headTitle('Sign in');
$form->get('user')->setAttributes([
    'style' => 'margin-bottom:20px',
    'class'=>'form-control', 
    'placeholder'=>'Login Name',
    'required' => true,
    //'autofocus' => true
    ])->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'style' => 'margin-bottom:20px',
    'class'=>'form-control', 
    'placeholder'=>'Password',
    'required' => true,
    ])->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

<div class="row" style="min-height: 500px; padding-top: 100px;">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Please sign in</h2>
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Incorrect login and/or password. 
                <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
            </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('user')); ?>
            <?= $this->formElement($form->get('user')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" style="margin-top: 20px;" type="submit">Sign in</button>
        </form>
    </div>
</div>