<style>
<!--
/* Divs message style */
.errorMessage {
    background-color: #ffbaba;
    border: 1px solid;
    color: #d8000c;    
    margin-top: 5px;
    padding: 10px;
    position: relative;	
	display: block;
    font-size: 10pt;	    
    vertical-align: middle;
	border-radius: 4px;	
}
.successMessage {
    background-color: #dff2bf;
    border: 1px solid;
    color: #4f8a10;    
    margin-top: 5px;
    padding: 10px;
    position: relative;	
	display: block;
    font-size: 10pt;	    
    vertical-align: middle;
	border-radius: 4px;
}
.closeMessage{
	cursor: pointer;
	font-size: 12pt;	
	height: 22px;
	position: absolute;
	right: 11px;
	text-align: center;
	top: 1px;	
}
-->
</style>
<script type="text/javascript">
var pwdResetUrl = baseUrl + '/user/set-vcode';
function closePwdResetMessage(){
	$("#pwdForgotMessage").hide(1000);
}
//JQUERY functions ------------------->
$(document).ready(function(){
	// Handles password reset action
	$("#btnPwdReset").click( function(){
		var email = $("#email");		
		if( $.trim(email.val()) == "" ){
			//alert('User name and password are required fileds please validate');
			var spanClose = "<div class='closeMessage' onclick='closePwdResetMessage();'>x</div>";
			$("#pwdForgotMessage").html('Email required'+spanClose).show().addClass('errorMessage').removeClass('successMessage');
			return false;
		} else {						
			// Process the form via JSON			
			$.post(pwdResetUrl, $("#frmPwdForgot").serialize(),
					 function(data){
		 				var spanClose = "<div class='closeMessage' onclick='closePwdResetMessage();'>x</div>";
		 				//alert(data);				 
				 		if (data.status == "success") {
				 			$("#frmPwdForgot").trigger("reset");				 			
				 			$("#pwdForgotMessage").html(data.message+spanClose).show().addClass('successMessage').removeClass('errorMessage');
				 			// Disable button
				 			$(this).attr('disabled', 'true');
					 	} else {
					 		//alert(data.error);					 		
					 		$("#pwdForgotMessage").html(data.message+spanClose).show().addClass('errorMessage').removeClass('successMessage');
					 	}			 		
	 			});
			return true;			
		}		
	});
});
</script>
<div class="row" style="min-height: 500px; padding-top: 100px;">
<div class="col-md-offset-4 col-md-3">
<form id='frmPwdForgot'>
	<h3 class="form-signin-heading">Please type your Email</h3>
	<div style="margin-top: 20px;"><input type="text" class="form-control" placeholder='Email' id="email" name="email" required autocomplete='off' value="" class='input' /></div>	
	<div style="margin-top: 20px;"><input type="button" id='btnPwdReset' name="Reset" value="Reset" class='btn btn-lg btn-primary btn-block'/></div>
	<div id='pwdForgotMessage'><br /></div>
</form>
</div>
</div>