<style type="text/css">
<!--
/* Divs message style */
.errorMessage {
    background-color: #ffbaba;
    border: 1px solid;
    color: #d8000c;    
    margin-top: 5px;
    padding: 10px;
    position: relative;	
	display: block;
    font-size: 10pt;	    
    vertical-align: middle;
	border-radius: 4px;	
}
.successMessage {
    background-color: #dff2bf;
    border: 1px solid;
    color: #4f8a10;    
    margin-top: 5px;
    padding: 10px;
    position: relative;	
	display: block;
    font-size: 10pt;	    
    vertical-align: middle;
	border-radius: 4px;
}
.closeMessage{
	cursor: pointer;
	font-size: 12pt;	
	height: 22px;
	position: absolute;
	right: 11px;
	text-align: center;
	top: 1px;	
}
-->
</style>
<script type="text/javascript">
<!--
//JavaScript functions ------------------->
function passedValidation(){	
	var passedCount = 0;
	if( $.trim($("#newPwd").val()) == '' || $.trim($("#confirmPwd").val()) == '' ){				
		passedCount = 1;
	} else if( $.trim($("#newPwd").val()) != $.trim($("#confirmPwd").val()) ){				
		passedCount = 1;			
	} 
	// If all fields are provided, let's post the form
    if( passedCount == 0 ) {
    	return true;
    } else {
    	return false;
    }
}
function closePwdChangeMessage(){
	$("#pwdChangeMessage").hide();	
}
//JQUERY functions ------------------->
$(document).ready(function(){
	// handles Save FAQ button action
	$("#btnPwdChange").click( function(){
		var passed = passedValidation();
		if( passed == true ){			
			// Submit topic			
			$.post( baseUrl + '/user/save-pwd', $("#frmPwdChange").serialize(),
					 function(data){				 
				 		if ( data.status=='success' ) {
							$("#pwdChangeMessage").html('Your password has been changed. Please wait...').show().addClass('successMessage').removeClass('errorMessage');
							// Let's wait a bit 
				 			setTimeout(function () {
				 				window.location = baseUrl+'/login';		
				 			  }, 2000);				 							 			
					 	} else {
					 		var spanClose = "<div class='closeMessage' onclick='closePwdChangeMessage();'>x</div>";
							$("#pwdChangeMessage").html(data.message+spanClose).show().addClass('errorMessage').removeClass('successMessage');
					 	}		 	
	 			}); 			
			return true;
		} else {
			var spanClose = "<div class='closeMessage' onclick='closePwdChangeMessage();'>x</div>";
			$("#pwdChangeMessage").html('Required fields, passwords must match'+spanClose).show().addClass('errorMessage').removeClass('successMessage');
			return false;			
		}
	});
});
//-->
</script>
<div class="row" style="min-height: 500px; padding-top: 100px;">
<div class="col-md-offset-4 col-md-3">
<form id='frmPwdChange'>
	<h3 class="form-signin-heading">Please type your new password</h3>
    <div><input type="hidden" id="userId" name="userId" value="<?php echo $this->userId; ?>"/></div>
    <div style="margin-top: 20px;"><input type="password" placeholder='New Password' id="newPwd" name="newPwd" required autocomplete='off' value="" class='form-control' /></div>
	<div style="margin-top: 20px;"><input type="password" placeholder='Confirm New Password' id="confirmPwd" name="confirmPwd" required autocomplete='off' value="" class='form-control' /></div>	
	<div style="margin-top: 20px;"><input type="button" id='btnPwdChange' name="Reset" value="Reset" class='btn btn-lg btn-primary btn-block'/></div>	
	<div id='pwdChangeMessage'><br /></div>
</form>
</div>
</div>