<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle( getenv('APP_NAME') )->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon-ntt.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))            
        ?>

        <!-- Scripts -->
        <?= $this->headScript()            
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <script type="text/javascript">
        	var baseUrl = '<?php echo $this->basepath();?>';
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>                    
                    <div class="hidden-xs" style="color: #ffffff">                        
                        <img src="<?= $this->basePath('img/overairlogo.png') ?>" height="48" title="<?php echo getenv('APP_NAME'); ?>&nbsp;<?= \Application\Module::VERSION ?>"/>&nbsp;NTT DATA
                    </div>
                </div>                                
            </div>
        </nav>        
        <div class="container" style="margin:10px auto 5px auto; padding:10px; width:99%;">        	
            <?= $this->content ?>            
        </div>
        <div>        	
            <footer>
                <p class="text-center"><?php echo getenv('APP_NAME');?>&nbsp;&nbsp;v<?php echo \Application\Module::VERSION;?>&nbsp;&copy;&nbsp;<?= date('Y') ?> <?= $this->translate('All rights reserved') ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
