<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle( getenv('APP_NAME') )->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon-ntt.ico'])            
            ->prependStylesheet($this->basePath('css/bootstrap-datepicker3.css'))
            ->prependStylesheet($this->basePath('css/bootcomplete.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))            
        ?>

        <!-- Scripts -->
        <?= $this->headScript()        
            ->prependFile($this->basePath('js/jquery.moveSelected.js'))
            ->prependFile($this->basePath('js/bootstrap-datepicker.min.js'))
            ->prependFile($this->basePath('js/waiting.dialog.js'))
            ->prependFile($this->basePath('js/jquery.bootcomplete.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))            
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
        <script type="text/javascript">
        	var baseUrl = '<?php echo $this->basePath();?>';
        </script>        
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header" style="height:55px">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>                    
                    <a class="navbar-brand hidden-xs hidden-sm hidden-md" href="<?= $this->url('home') ?>">                        
                        <img src="<?= $this->basePath('img/overairlogo.png') ?>" style="margin-top:-10px;" height="48" title="<?php echo getenv('APP_NAME'); ?>&nbsp;<?= \Application\Module::VERSION ?>"/>&nbsp;NTT DATA
                    </a>
                </div>
                <div class="collapse navbar-collapse">                
                	<?php // See /module/Application/config/module.config.php for details, add this: ?>
    				<?php echo $this->navigation('navigation')->menu()->setPartial('partial/custom-menu'); ?>    				
                </div>
            </div>
        </nav>
<?php if( !empty($this->userEmail) ){?>        
        <div class="text-right" style="font-weight:bold; with:80%; margin-right:20px; padding-top:5px;">        	        	
        	<span><?php echo 'Logged in as '.stripslashes( $this->userEmail );?></span>
        </div>
<?php }?>                
        <div class="container" style="margin:10px auto 5px auto; border:solid 2px #4e88c7; border-radius:4px; padding:10px; width:99%;">
        	<div class='container'><!-- Lets display messages here shall we ? -->
                <div id='divLoading' class='text-center' style='display:none;'>
                    <img style="border: none; height:30px; width:30px;" src='<?php echo $this->basepath("/img/loading.gif");?>'>
                    <span style="font-size:16px;">Loading, please wait...</span>
                </div>            
                <div id='divSiteMessage' class="alert" style="display: none;"> 
                    <a class="close" onclick="$('#divSiteMessage').hide()">&times;</a>  
                    <span id='spanSiteMessage'>Site Message goes here.</span>                  
                </div>
            </div><!-- Lets display messages here shall we ? -->
            <?= $this->content ?>            
        </div>
        <div>        	
            <footer>
                <p class="text-center"><?php echo getenv('APP_NAME');?><?php echo (getenv('APP_ENV')=='production') ? ' ' : '-'.ucfirst(getenv('APP_ENV'));?>&nbsp;&nbsp;v<?php echo \Application\Module::VERSION;?>&nbsp;&copy;&nbsp;<?= date('Y') ?> <?= $this->translate('All rights reserved') ?></p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
